import numpy as np
import scipy.signal as signal
import matplotlib.pyplot as plt
import json

# ============================================================
# User parameters
# ============================================================

NYQUIST_HZ = 24000.0
FS_HZ = NYQUIST_HZ * 2.0

ORDER = 4
PASSBAND_RIPPLE_DB = 0.1
STOPBAND_ATTEN_DB = 80.0

TARGET_NYQUIST_HZ = 0.25 * NYQUIST_HZ
FC_HZ = TARGET_NYQUIST_HZ * 0.25

PLOT_F_MIN = 20.0
PLOT_F_MAX = 24000.0
PLOT_DB_MIN = -120.0
PLOT_DB_MAX = 10.0

# ============================================================
# Design 4th-order elliptic low-pass IIR
# ============================================================

b, a = signal.ellip(
    N=ORDER,
    rp=PASSBAND_RIPPLE_DB,
    rs=STOPBAND_ATTEN_DB,
    Wn=FC_HZ,
    btype="lowpass",
    analog=False,
    output="ba",
    fs=FS_HZ,
)

# Optional: SOS form for numerical inspection / alternative implementation
sos = signal.ellip(
    N=ORDER,
    rp=PASSBAND_RIPPLE_DB,
    rs=STOPBAND_ATTEN_DB,
    Wn=FC_HZ,
    btype="lowpass",
    analog=False,
    output="sos",
    fs=FS_HZ,
)

# ============================================================
# Frequency response
# ============================================================

w, h = signal.freqz(b, a, worN=262144, fs=FS_HZ)

mag_db = 20.0 * np.log10(np.maximum(np.abs(h), 1e-300))

def db_at(freq_hz):
    idx = np.argmin(np.abs(w - freq_hz))
    return mag_db[idx]

print("============================================")
print("4th-order elliptic low-pass")
print("============================================")
print(f"FS_HZ                = {FS_HZ:.9g}")
print(f"NYQUIST_HZ           = {NYQUIST_HZ:.9g}")
print(f"TARGET_NYQUIST_HZ    = {TARGET_NYQUIST_HZ:.9g}")
print(f"FC_HZ                = {FC_HZ:.9g}")
print(f"Passband ripple      = {PASSBAND_RIPPLE_DB:.9g} dB")
print(f"Stopband attenuation = {STOPBAND_ATTEN_DB:.9g} dB")
print()
print(f"Gain at FC_HZ             {FC_HZ:.3f} Hz = {db_at(FC_HZ):.6f} dB")
print(f"Gain at target Nyquist    {TARGET_NYQUIST_HZ:.3f} Hz = {db_at(TARGET_NYQUIST_HZ):.6f} dB")
print(f"Gain at Nyquist           {NYQUIST_HZ:.3f} Hz = {db_at(NYQUIST_HZ):.6f} dB")
print()

print("b coefficients:")
print(b)
print()
print("a coefficients:")
print(a)
print()

# ============================================================
# Export coefficients
# ============================================================

coeff_data = {
    "fs_hz": FS_HZ,
    "nyquist_hz": NYQUIST_HZ,
    "target_nyquist_hz": TARGET_NYQUIST_HZ,
    "fc_hz": FC_HZ,
    "order": ORDER,
    "passband_ripple_db": PASSBAND_RIPPLE_DB,
    "stopband_atten_db": STOPBAND_ATTEN_DB,
    "b": b.tolist(),
    "a": a.tolist(),
    "sos": sos.tolist(),
}

with open("ellip4_lowpass_coeffs.json", "w", encoding="utf-8") as f:
    json.dump(coeff_data, f, indent=4)

with open("ellip4_lowpass_coeffs.h", "w", encoding="utf-8") as f:
    f.write("#ifndef ELLIP4_LOWPASS_COEFFS_H\n")
    f.write("#define ELLIP4_LOWPASS_COEFFS_H\n\n")

    f.write("// Generated by design_ellip4_lowpass.py\n")
    f.write(f"// FS_HZ             = {FS_HZ:.9g}\n")
    f.write(f"// NYQUIST_HZ        = {NYQUIST_HZ:.9g}\n")
    f.write(f"// TARGET_NYQUIST_HZ = {TARGET_NYQUIST_HZ:.9g}\n")
    f.write(f"// FC_HZ             = {FC_HZ:.9g}\n")
    f.write(f"// ORDER             = {ORDER}\n")
    f.write(f"// RP                = {PASSBAND_RIPPLE_DB:.9g} dB\n")
    f.write(f"// RS                = {STOPBAND_ATTEN_DB:.9g} dB\n\n")

    f.write("static const float kEllip4B[5] = {\n")
    for i, v in enumerate(b):
        comma = "," if i < len(b) - 1 else ""
        f.write(f"    {v:.15g}f{comma}\n")
    f.write("};\n\n")

    f.write("static const float kEllip4A[5] = {\n")
    for i, v in enumerate(a):
        comma = "," if i < len(a) - 1 else ""
        f.write(f"    {v:.15g}f{comma}\n")
    f.write("};\n\n")

    f.write("#endif\n")

print("Exported:")
print("  ellip4_lowpass_coeffs.json")
print("  ellip4_lowpass_coeffs.h")

# ============================================================
# Plot
# ============================================================

plt.figure(figsize=(10, 5.6))

plt.semilogx(w, mag_db, linewidth=1.2)

plt.axvline(
    TARGET_NYQUIST_HZ,
    linestyle="--",
    linewidth=1.0,
    label=f"Target Nyquist = {TARGET_NYQUIST_HZ:.1f} Hz",
)

plt.axvline(
    FC_HZ,
    linestyle=":",
    linewidth=1.0,
    label=f"fc = {FC_HZ:.1f} Hz",
)

plt.xlim(PLOT_F_MIN, PLOT_F_MAX)
plt.ylim(PLOT_DB_MIN, PLOT_DB_MAX)

plt.grid(True, which="both", linestyle=":", linewidth=0.6)
plt.xlabel("Frequency / Hz")
plt.ylabel("Magnitude / dB")
plt.title("4th-order elliptic low-pass response")
plt.legend(loc="best")

plt.tight_layout()
plt.savefig("ellip4_lowpass_response.png", dpi=160)
plt.show()